// Code generated by capnpc-go. DO NOT EDIT.

package proto

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type WatchDogMetricExt struct{ capnp.Struct }

// WatchDogMetricExt_TypeID is the unique identifier for the type WatchDogMetricExt.
const WatchDogMetricExt_TypeID = 0xec5bf5790a3585da

func NewWatchDogMetricExt(s *capnp.Segment) (WatchDogMetricExt, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return WatchDogMetricExt{st}, err
}

func NewRootWatchDogMetricExt(s *capnp.Segment) (WatchDogMetricExt, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return WatchDogMetricExt{st}, err
}

func ReadRootWatchDogMetricExt(msg *capnp.Message) (WatchDogMetricExt, error) {
	root, err := msg.RootPtr()
	return WatchDogMetricExt{root.Struct()}, err
}

func (s WatchDogMetricExt) String() string {
	str, _ := text.Marshal(0xec5bf5790a3585da, s.Struct)
	return str
}

func (s WatchDogMetricExt) Set() bool {
	return s.Struct.Bit(0)
}

func (s WatchDogMetricExt) SetSet(v bool) {
	s.Struct.SetBit(0, v)
}

func (s WatchDogMetricExt) Val() uint32 {
	return s.Struct.Uint32(4)
}

func (s WatchDogMetricExt) SetVal(v uint32) {
	s.Struct.SetUint32(4, v)
}

// WatchDogMetricExt_List is a list of WatchDogMetricExt.
type WatchDogMetricExt_List struct{ capnp.List }

// NewWatchDogMetricExt creates a new list of WatchDogMetricExt.
func NewWatchDogMetricExt_List(s *capnp.Segment, sz int32) (WatchDogMetricExt_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return WatchDogMetricExt_List{l}, err
}

func (s WatchDogMetricExt_List) At(i int) WatchDogMetricExt {
	return WatchDogMetricExt{s.List.Struct(i)}
}

func (s WatchDogMetricExt_List) Set(i int, v WatchDogMetricExt) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s WatchDogMetricExt_List) String() string {
	str, _ := text.MarshalList(0xec5bf5790a3585da, s.List)
	return str
}

// WatchDogMetricExt_Promise is a wrapper for a WatchDogMetricExt promised by a client call.
type WatchDogMetricExt_Promise struct{ *capnp.Pipeline }

func (p WatchDogMetricExt_Promise) Struct() (WatchDogMetricExt, error) {
	s, err := p.Pipeline.Struct()
	return WatchDogMetricExt{s}, err
}

const schema_e6c88aaab6a1209e = "x\xda\x120q`\x12d\x8dg`\x08dae\xfb" +
	"\x7f\xab\xd5\x94\xab\xf2k\xf4\x1b\x86@~F\xc6\xff\xf3" +
	"\x14\x16n[\xd5u\xe2\x19\x03\x0b;\x03\x83\xa1(\x17" +
	"\xa3\xa0*;\x03\x83\xa0b9\x03\xe3\xff\xf2\xc4\x92\xe4" +
	"\x8c\x94\xfctf\xbd\xe4\xc4\x82\xbc\x02\xabp\x10\xdf%" +
	"?\xdd7\xb5\xa4(3\xd9\xb5\xa2\x84\x81!\x80\x911" +
	"\x90\x83\x99\x85\x81\x81\x85\x91\x81APS\x89\x81!P" +
	"\x85\x991\xd0\x80\x89Q\x90\x91Q\x84\x11$\xa8\x0b\x12" +
	"\xd4`f\x0c4abd/N-add`b" +
	"dd`d/K\xcca\xe4``b\xe4``\x04" +
	"\x04\x00\x00\xff\xffI_\"\x13"

func init() {
	schemas.Register(schema_e6c88aaab6a1209e,
		0xec5bf5790a3585da)
}
